# Generated by Django 4.2.7 on 2024-03-24 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Categorie',
        ),
        migrations.RenameModel(
            old_name='Clients',
            new_name='Client',
        ),
        migrations.RenameModel(
            old_name='Commandes',
            new_name='Commande',
        ),
        migrations.RenameModel(
            old_name='Produits',
            new_name='Produit',
        ),
    ]
