# Generated by Django 4.2.7 on 2024-04-16 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0005_adressefacturation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adressefacturation',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adressefacturation',
            name='code_postal',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adressefacturation',
            name='rue',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adressefacturation',
            name='titre',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adressefacturation',
            name='ville',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
