# Generated by Django 4.2.7 on 2024-04-16 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0006_alter_adressefacturation_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adressefacturation',
            name='User',
            field=models.OneToOneField(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adressefacturation',
            name='code_postal',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='adressefacturation',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='adressefacturation',
            name='rue',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='adressefacturation',
            name='titre',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='adressefacturation',
            name='ville',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
