# Generated by Django 4.2.7 on 2024-04-22 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_adresselivraison'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='client',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
