# Generated by Django 4.2.7 on 2024-05-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_commande_client_delete_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adressefacturation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='adresselivraison',
            name='email',
        ),
        migrations.AddField(
            model_name='adressefacturation',
            name='Pays',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='adresselivraison',
            name='Pays',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
