# Generated by Django 4.2.7 on 2024-05-27 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_adressefacturation_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adressefacturation',
            old_name='Pays',
            new_name='pays',
        ),
        migrations.RenameField(
            model_name='adressefacturation',
            old_name='User',
            new_name='user',
        ),
    ]
