# Generated by Django 4.2.7 on 2024-05-27 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_pays_adressefacturation_pays_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adressefacturation',
            name='titre',
        ),
    ]
