# Generated by Django 4.2.7 on 2024-05-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_adressefacturation_titre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adresselivraison',
            old_name='Pays',
            new_name='livraison_Pays',
        ),
        migrations.RenameField(
            model_name='adresselivraison',
            old_name='code_postal',
            new_name='livraison_titre',
        ),
        migrations.RenameField(
            model_name='adresselivraison',
            old_name='user',
            new_name='livraison_user',
        ),
        migrations.RenameField(
            model_name='adresselivraison',
            old_name='rue',
            new_name='livraison_ville',
        ),
        migrations.RemoveField(
            model_name='adresselivraison',
            name='titre',
        ),
        migrations.RemoveField(
            model_name='adresselivraison',
            name='ville',
        ),
        migrations.AddField(
            model_name='adresselivraison',
            name='livraison_code_postal',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adresselivraison',
            name='livraison_rue',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
