# Generated by Django 4.2.7 on 2024-05-27 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rename_pays_adresselivraison_livraison_pays_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adresselivraison',
            old_name='livraison_user',
            new_name='user',
        ),
    ]
