# Generated by Django 4.2.7 on 2024-05-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_rename_livraison_pays_adresselivraison_livraison_pays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='is_promo',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='promo_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
