# Generated by Django 4.2.7 on 2024-06-01 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_produit_is_promo_alter_produit_promo_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commande',
        ),
    ]
