# Generated by Django 4.2.7 on 2024-06-01 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0002_rename_order_commande_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='address',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='date_ordered',
        ),
        migrations.RemoveField(
            model_name='commandearticle',
            name='order',
        ),
        migrations.RemoveField(
            model_name='commandearticle',
            name='user',
        ),
        migrations.AddField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='expedie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commande',
            name='livraison_code_postal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='livraison_pays',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='livraison_rue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='livraison_titre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='livraison_ville',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='commandearticle',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='panier.commande'),
        ),
    ]
