# Generated by Django 4.2.7 on 2024-06-01 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panier', '0003_remove_commande_address_remove_commande_date_ordered_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='date_commande',
            new_name='date_ordered',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='expedie',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='livraison_code_postal',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='livraison_pays',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='livraison_rue',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='livraison_titre',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='livraison_ville',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='total',
        ),
        migrations.AddField(
            model_name='commande',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='commandearticle',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commandearticle',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panier.commande'),
        ),
    ]
