# Generated by Django 4.2.7 on 2024-06-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0005_alter_commande_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_ordered',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
