# Generated by Django 4.2.7 on 2024-06-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0006_alter_commande_address_alter_commande_date_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='prix_total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
