# Generated by Django 4.2.7 on 2024-06-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0007_commande_prix_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='address',
            field=models.TextField(max_length=15000),
        ),
    ]
