# Generated by Django 4.2.7 on 2024-06-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0008_alter_commande_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
