# Generated by Django 4.2.7 on 2024-06-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0009_alter_commande_email_alter_commande_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commandearticle',
            old_name='quantite',
            new_name='quantitee',
        ),
        migrations.AlterField(
            model_name='commande',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='commande',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
